name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install JBang
      run: curl -Ls https://sh.jbang.dev | bash -s - app setup
    - run: ~/.jbang/bin/jbang trust add https://github.com/apache/camel/
    - run: docker run -d -p 8161:8161 -p 61616:61616 -p 5672:5672 -e ANONYMOUS_LOGIN=true apache/activemq-artemis:2.38.0
    - run: docker compose -f tests/compose.yaml up --wait
    - run: cd publisher && ~/.jbang/bin/jbang camel@apache/camel run application.properties ../tests/publisher.test.properties &
    - run: cd consumer && ~/.jbang/bin/jbang camel@apache/camel run application.properties ../tests/consumer.test.properties &
    - name: Install dependencies
      run: npm install -g yarn && yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      run: yarn playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
