name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install JBang
      run: curl -Ls https://sh.jbang.dev | bash -s - app setup
    - run: ~/.jbang/bin/jbang trust add https://github.com/apache/camel/
    - run: docker compose -f tests/compose.yaml up -d
    - run: ~/.jbang/bin/jbang -Dcamel.jbang.version=4.12.0-SNAPSHOT camel@apache/camel run application.properties tests/application.test.properties &
    - name: Install dependencies
      run: npm install -g yarn && yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      run: yarn playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
